### ISSUE TITLE
Incorrect component in README

### ISSUE THREAD

**Issue by brandong1** [learn-co-curriculum/react-static-components-lab#18]
The README says:

In total, App needs to render three children components:

1. CatComponent
2. GraceHopperQuoteComponent
3. MouseComponent

index-test.js has a test that says:
	expect(wrapper.text()).to.include('<EinsteinQuoteComponent />');
	});

Either test should be updated to replace EinsteinQuoteComponent with GraceHopperQuoteComponent, or README and filenames should be changed to reflect GraceHopperQuoteComponent

**Comment by kwebster2** [comment]
@maxwellbenton it looks like b675de1dc46a4fa7d96d801e682b5fbedeb44433 already addressed this, but has not been pushed to the Full Stack V8 track.

**Comment by maxwellbenton** [comment]
Hi @brandong1 and @kwebster2,

Thank you for providing this feedback. Looks like this repository fell out alignment with the learn-co-student versions, so the fix here never made it downstream. I've manually pushed the recent commits to the V8 versions (`v-000` and `online-web-sp-000`), so this should be resolved going forward.

Sorry for any frustration this may have caused and thank you for reporting this!
