### ISSUE TITLE
non-technical cultural sensitivity issue to consider

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/react-static-components-lab#2]
Hey, About the Henry Ford quote in this lab, Henry Ford was a well-known racist and anti-semite. You may consider changing out the quote for someone else. Not that many people know this about Ford, but those of us who do may definitely feel weirded out by seeing him here, especially post-pittsburgh shootings. Popping in a link: https://www.pbs.org/wgbh/americanexperience/features/henryford-antisemitism/. Thanks for considering!

**Comment by maxwellbenton** [comment]
Thank you @MiriamPeskowitz for bringing this to our attention. We've removed references to Ford from the lesson and replaced them with a different quote.
