### ISSUE TITLE
Lab requires knowledge of material not yet covered

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/react-static-components-lab#20]
In order to pass this lab, you have to know how to use named exports.

However, named exports have not been covered in any of the React lessons before this lab.

**Comment by lizbur10** [comment]
Thanks for bringing this to our attention @Sdcrouse ! This issue has been fixed 💙

**Comment by Sdcrouse** [comment]
Thanks, Liz! I appreciate it.
