### ISSUE TITLE
Issue with lesson instructions

### ISSUE THREAD

**Issue by slaraja** [learn-co-curriculum/react-static-components-lab#38]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/2073/assignments/68987?module_item_id=134258
## What should be changed?

This line should be deleted: All of our work will be done in src/App.js, the rest of the components/source files shouldn't need any alterations.

## Additional context

I spent hours trying to debug the issue in app.js and after asking AAQ, I realized I needed to alter the grace hopper file. Super frustrating because the lesson said to only alter app.js.

**Comment by lizbur10** [comment]
Hi @slaraja ! Thank you for bringing this to our attention! The problem was that the lab was assuming knowledge about named exports, which isn't covered until later in the section. The instructions have been updated to fix the issue.

Thanks for contributing to the Flatiron School curriculum 💙
